spring.datasource.url=jdbc:mysql://mysql-da00eec-academichub.d.aivencloud.com:16000/defaultdb?sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080