spring.datasource.url=jdbc:postgresql://dpg-d7i5p0aqqhas738shh10-a:5432/academic_dfrh
spring.datasource.username=academic_dfrh_user
spring.datasource.password=0P8JSI6mDqpUXBDWaHccGPgAhBKoInLD

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update